package com.synxapps.bluewave.enums;

public enum Interests {
	FOOTBALL, CYCLING, TRAVEL, VIDEOGAMES, TVSHOWS, ANIME, MANGA, PROGRAMMING,
	PARTY, DANCING, MUSIC, MUSICIAN, POLITICS, MOVIES, TECHNOLOGY, DOGS, CATS, EXOTICPETS, NULL;
	//TODO: Add more
}
